version: '3.8'
services:
  frontend:
    image: node:20-alpine
    container_name: omnicard-frontend
    working_dir: /app
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - "8080:3000"
    command: sh -c "npm install && npm run dev"
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - omnicard-network
networks:
  omnicard-network:
    external: true 