global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'omnicard-backend'
    static_configs:
      - targets: ['backend:8001']
  - job_name: 'mongodb'
    static_configs:
      - targets: ['mongodb:27017']
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq:15672']
  - job_name: 'ollama'
    static_configs:
      - targets: ['ollama:11434'] 