global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'api-server'
    static_configs:
      - targets: ['api-server:8001']

  - job_name: 'mongodb'
    static_configs:
      - targets: ['mongodb:27018']

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379'] 